on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
        working-directory: ${{ inputs.config-path }}
      
