on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      ref:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    if: ${{ github.ref_name == inputs.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: pwd
        working-directory: ${{ inputs.config-path }}
      
